In [1]:
import pandas as pd
import numpy as np
import os
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.model_selection import train_test_split

In [2]:
# 1. Load Data

data = pd.read_csv("Daily_Water_Intake.csv")

print("Dataset loaded successfully")

Dataset loaded successfully


In [3]:
# 2. DATA CLEANING

# Remove extra spaces from column names
data.columns = data.columns.str.strip()

# Checking missing values
print("\nMissing Values per Column:")
print(data.isnull().sum())


Missing Values per Column:
Age                            0
Gender                         0
Weight (kg)                    0
Daily Water Intake (liters)    0
Physical Activity Level        0
Weather                        0
Hydration Level                0
dtype: int64


In [4]:
# 3. Data Cleaning

# Convert numerical columns to proper numeric type
numeric_cols = ['Age', 'Weight (kg)', 'Daily Water Intake (liters)']

for col in numeric_cols:
    data[col] = pd.to_numeric(data[col], errors='coerce')

# Fill missing numerical values with mean
data[numeric_cols] = data[numeric_cols].fillna(data[numeric_cols].mean())

In [5]:
# 4. Handling Categorical Data

le = LabelEncoder()

data['Gender'] = le.fit_transform(data['Gender'])
data['Weather'] = le.fit_transform(data['Weather'])
data['Hydration Level'] = le.fit_transform(data['Hydration Level'])

In [ ]:
# Convert all object/string columns into numeric

label_encoder = LabelEncoder()

for col in X.select_dtypes(include='object').columns:
    X[col] = label_encoder.fit_transform(X[col].astype(str))

In [ ]:
# Feature Scaling

scaler = StandardScaler()

X_scaled = scaler.fit_transform(X)

In [ ]:
# Splitting Dataset

X_train, X_test, y_train, y_test = train_test_split(
    X_scaled,
    y,
    test_size=0.2,
    random_state=42
)

print("Dataset split successfully")

Dataset split successfully


In [ ]:
print(X_scaled.shape)

(30000, 6)


In [ ]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

# checking train & test data
print(X_train[:5])

print(y_train[:5])

       Age  Gender  Weight (kg)  Daily Water Intake (liters)  \
21753   55       0           90                         2.87   
251     20       0           62                         1.50   
22941   22       0           87                         3.43   
618     56       1           62                         3.03   
17090   32       0           83                         3.54   

       Physical Activity Level  Weather  
21753                        2        0  
251                          1        0  
22941                        0        2  
618                          2        1  
17090                        0        0  
21753    0
251      1
22941    0
618      0
17090    0
Name: Hydration Level, dtype: int64


In [ ]:
# Convert train and test data into DataFrames

X_train_df = pd.DataFrame(X_train, columns=X.columns)

X_test_df = pd.DataFrame(X_test, columns=X.columns)

y_train_df = pd.DataFrame(y_train, columns=['Hydration Level'])

y_test_df = pd.DataFrame(y_test, columns=['Hydration Level'])

In [ ]:
# Combine X & Y

train_data = pd.concat([X_train_df, y_train_df], axis=1)

test_data = pd.concat([X_test_df, y_test_df], axis=1)

In [ ]:
# Convert all object/string columns into numeric

label_encoder = LabelEncoder()

for col in X.select_dtypes(include='object').columns:
    
    X[col] = label_encoder.fit_transform(X[col].astype(str))


# Feature Scaling

scaler = StandardScaler()

X_scaled = scaler.fit_transform(X)


# Splitting Dataset

X_train, X_test, y_train, y_test = train_test_split(
    
    X_scaled,
    y,
    test_size=0.2,
    random_state=42
)

print("Dataset split successfully")


# Checking train & test data

print(X_train[:5])

print(y_train[:5])


# Convert to DataFrames and Save

X_train_df = pd.DataFrame(X_train, columns=X.columns)

X_test_df = pd.DataFrame(X_test, columns=X.columns)

y_train_df = pd.DataFrame(y_train).reset_index(drop=True)

y_test_df = pd.DataFrame(y_test).reset_index(drop=True)


# Combine X & Y

train_data = pd.concat([X_train_df, y_train_df], axis=1)

test_data = pd.concat([X_test_df, y_test_df], axis=1)


# Save train and test datasets

train_data.to_csv("water_train_data.csv", index=False)

test_data.to_csv("water_test_data.csv", index=False)

print("Success! Processed data saved.")

Dataset split successfully
[[ 0.7688894  -1.00213561  0.70160902  0.0210116   1.23118918 -1.22294851]
 [-1.56464781 -1.00213561 -0.79215229 -1.61868035  0.00608469 -1.22294851]
 [-1.43130282 -1.00213561  0.54156316  0.69125064 -1.21901981  1.23153921]
 [ 0.83556189  0.99786894 -0.79215229  0.21250846  1.23118918  0.00429535]
 [-0.76457791 -1.00213561  0.32816869  0.82290474 -1.21901981 -1.22294851]]
21753    0
251      1
22941    0
618      0
17090    0
Name: Hydration Level, dtype: int64
Success! Processed data saved.
